/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type MemberReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'member'
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  president?: MemberReference
  editorInChief?: MemberReference
}

export type Tag = {
  _id: string
  _type: 'tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: RequiredFormattedString
  slug: Slug
  description: RequiredFormattedText
  metaInfo?: MetaInfo
  copypaste?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type MetaInfo = {
  _type: 'metaInfo'
  ogTitle?: FormattedString
  ogTags?: Array<
    {
      _key: string
    } & SeoMetadataTagText
  >
  ogDescription?: FormattedText
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: RequiredFormattedString
    _type: 'image'
  }
}

export type RequiredFormattedText = string

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type RequiredFormattedString = string

export type CommitteeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'committee'
}

export type Member = {
  _id: string
  _type: 'member'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: RequiredFormattedString
  slug: Slug
  year?: number
  committee?: CommitteeReference
  netid?: FormattedString
  bio?: FormattedText
  from?: FromLocation
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  handles?: Handles
  metaInfo?: MetaInfo
  copypaste?: string
}

export type Handles = {
  _type: 'handles'
  twitter?: FormattedString
  instagram?: FormattedString
  facebook?: FormattedString
  linkedin?: FormattedString
  github?: FormattedString
  website?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type FromLocation = {
  _type: 'fromLocation'
  country?:
    | 'AF'
    | 'AL'
    | 'DZ'
    | 'AD'
    | 'AO'
    | 'AG'
    | 'AR'
    | 'AM'
    | 'AU'
    | 'AT'
    | 'AZ'
    | 'BS'
    | 'BH'
    | 'BD'
    | 'BB'
    | 'BY'
    | 'BE'
    | 'BZ'
    | 'BJ'
    | 'BT'
    | 'BO'
    | 'BA'
    | 'BW'
    | 'BR'
    | 'BN'
    | 'BG'
    | 'BF'
    | 'BI'
    | 'CV'
    | 'KH'
    | 'CM'
    | 'CA'
    | 'CF'
    | 'TD'
    | 'CL'
    | 'CN'
    | 'CO'
    | 'KM'
    | 'CG'
    | 'CD'
    | 'CR'
    | 'HR'
    | 'CU'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'DJ'
    | 'DM'
    | 'DO'
    | 'EC'
    | 'EG'
    | 'SV'
    | 'GQ'
    | 'ER'
    | 'EE'
    | 'SZ'
    | 'ET'
    | 'FJ'
    | 'FI'
    | 'FR'
    | 'GA'
    | 'GM'
    | 'GE'
    | 'DE'
    | 'GH'
    | 'GR'
    | 'GD'
    | 'GT'
    | 'GN'
    | 'GW'
    | 'GY'
    | 'HT'
    | 'HN'
    | 'HU'
    | 'IS'
    | 'IN'
    | 'ID'
    | 'IR'
    | 'IQ'
    | 'IE'
    | 'IL'
    | 'IT'
    | 'JM'
    | 'JP'
    | 'JO'
    | 'KZ'
    | 'KE'
    | 'KI'
    | 'KP'
    | 'KR'
    | 'KW'
    | 'KG'
    | 'LA'
    | 'LV'
    | 'LB'
    | 'LS'
    | 'LR'
    | 'LY'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'MG'
    | 'MW'
    | 'MY'
    | 'MV'
    | 'ML'
    | 'MT'
    | 'MH'
    | 'MR'
    | 'MU'
    | 'MX'
    | 'FM'
    | 'MD'
    | 'MC'
    | 'MN'
    | 'ME'
    | 'MA'
    | 'MZ'
    | 'MM'
    | 'NA'
    | 'NR'
    | 'NP'
    | 'NL'
    | 'NZ'
    | 'NI'
    | 'NE'
    | 'NG'
    | 'MK'
    | 'NO'
    | 'OM'
    | 'PK'
    | 'PW'
    | 'PA'
    | 'PG'
    | 'PY'
    | 'PE'
    | 'PH'
    | 'PL'
    | 'PT'
    | 'QA'
    | 'RO'
    | 'RU'
    | 'RW'
    | 'KN'
    | 'LC'
    | 'VC'
    | 'WS'
    | 'SM'
    | 'ST'
    | 'SA'
    | 'SN'
    | 'RS'
    | 'SC'
    | 'SL'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'SB'
    | 'SO'
    | 'ZA'
    | 'SS'
    | 'ES'
    | 'LK'
    | 'SD'
    | 'SR'
    | 'SE'
    | 'CH'
    | 'SY'
    | 'TJ'
    | 'TH'
    | 'TL'
    | 'TG'
    | 'TO'
    | 'TT'
    | 'TN'
    | 'TR'
    | 'TM'
    | 'TV'
    | 'UG'
    | 'UA'
    | 'AE'
    | 'GB'
    | 'US'
    | 'UY'
    | 'UZ'
    | 'VU'
    | 'VE'
    | 'VN'
    | 'YE'
    | 'ZM'
    | 'ZW'
  region?: FormattedString
  city?: FormattedString
}

export type FormattedText = string

export type FormattedString = string

export type Committee = {
  _id: string
  _type: 'committee'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: RequiredFormattedString
  slug: Slug
  description: RequiredFormattedText
  useCustomCss?: boolean
  metaInfo?: MetaInfo
  copypaste?: string
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type SeriesReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'series'
}

export type TagReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'tag'
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: RequiredFormattedString
  slug: Slug
  subtitle?: FormattedText
  date: string
  updatedDate?: string
  category: CategoryReference
  series?: SeriesReference
  tags?: Array<
    {
      _key: string
    } & TagReference
  >
  authors: Array<
    {
      _key: string
    } & MemberReference
  >
  media?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  }
  abstract?: FormattedText
  content: Content
  useCustomCss?: boolean
  metaInfo?: MetaInfo
}

export type Content = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote' | 'blockComment'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      title?: FormattedString
      description?: FormattedText
      alt: RequiredFormattedString
      _type: 'image'
      _key: string
    }
  | ({
      _key: string
    } & EmbeddedLink)
>

export type Series = {
  _id: string
  _type: 'series'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: RequiredFormattedString
  slug: Slug
  description: RequiredFormattedText
  useCustomCss?: boolean
  metaInfo?: MetaInfo
  copypaste?: string
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: RequiredFormattedString
  slug: Slug
  description: RequiredFormattedText
  useCustomCss?: boolean
  metaInfo?: MetaInfo
  copypaste?: string
}

export type SeoMetadataTagText = string

export type AccessibleImage = {
  _type: 'accessibleImage'
  media?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    description?: FormattedText
    attributions?: FormattedString
    _type: 'image'
  }
}

export type DateInfo = {
  _type: 'dateInfo'
  published: string
  updated?: string
}

export type EmbeddedLink = {
  _type: 'embeddedLink'
  contentUrl: string
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | MemberReference
  | AboutPage
  | Tag
  | SanityImageAssetReference
  | MetaInfo
  | RequiredFormattedText
  | Slug
  | RequiredFormattedString
  | CommitteeReference
  | Member
  | Handles
  | SanityImageCrop
  | SanityImageHotspot
  | FromLocation
  | FormattedText
  | FormattedString
  | Committee
  | CategoryReference
  | SeriesReference
  | TagReference
  | Article
  | Content
  | Series
  | Category
  | SeoMetadataTagText
  | AccessibleImage
  | DateInfo
  | EmbeddedLink
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
