# Modified and retrieved from:
# https://github.com/payloadcms/payload/blob/main/.github/actions/setup/action.yml
name: Setup node and yarn
description: |
  Configures Node, yarn, cache, then installs deps

inputs:
  node-version:
    description: Node version
    required: true
    default: 22.4.1
  yarn-version:
    description: Yarn version
    required: true
    default: 4.5.3
  yarn-run-install:
    description: Whether to run yarn install
    required: false
    default: true
  yarn-restore-cache:
    description: Whether to restore yarn cache
    required: false
    default: true
  yarn-install-cache-key:
    description: The cache key for the yarn install
    default: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

  outputs:
    yarn-store-path:
      description: The resolved yarn cache path
    yarn-install-cache-key:
      description: The cache key used for the yarn install cache

  runs:
    using: composite
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node@${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn

      # Yarn installation
      - name: Enable corepack
        run: corepack enable

      - name: Install yarn
        run: corepack install --global ${{ inputs.yarn-version }}

      - name: Set yarn version
        run: corepack use ${{ inputs.yarn-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        shell: bash
        run: |
          STORE_PATH=$(yarn config get cacheFolder)
          echo "STORE_PATH=$STORE_PATH" >> "$GITHUB_OUTPUT"
          echo "Yarn store path resolved to: $STORE_PATH"

      - name: Restore yarn install cache
        if: ${{ inputs.yarn-restore-cache == 'true' }}
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: ${{ inputs.yarn-run-install == 'true' }}
        run: yarn --immutable

      - run: |
          echo "yarn-install-cache-key=${{ inputs.yarn-install-cache-key }}" >> "$GITHUB_ENV"

      # Cache dependencies.
      # Retrieved from: https://github.com/actions/cache/blob/main/examples.md#node---yarn
