approvedGitRepositories:
  - "**"

cacheFolder: ./.yarn/cache

cacheMigrationMode: match-spec

changesetBaseRefs:
  - dev
  - origin/dev

changesetIgnorePatterns:
  - "**/*.test.{ts,tsx,js,jsx}"
  - "**/*.spec.{ts,tsx,js,jsx}"
  - "**/*.md"
  - "**/*.nix"
  - "**/*.prettierignore"

compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: true

enableTelemetry: false

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nodeLinker: node-modules

preferInteractive: true

preferReuse: true

plugins:
  - path: .yarn/plugins/plugin-disable-typescript-compat.cjs
    spec: "plugin-disable-typescript-compat"
