cacheFolder: ./.yarn/cache
cacheMigrationMode: match-spec
compressionLevel: 0
enableGlobalCache: false
enableTelemetry: false
nmHoistingLimits: workspaces
nmMode: hardlinks-local
nodeLinker: node-modules
preferInteractive: true
preferReuse: true
defaultSemverRangePrefix: ""
changesetBaseRefs:
  - "dev"
  - "origin/dev"
changesetIgnorePatterns:
  - "**/*.test.{ts,tsx,js,jsx}"
  - "**/*.spec.{ts,tsx,js,jsx}"
  - "**/*.md"
  - "**/*.nix"
