# nodeLinker is used because some node packages are not yet supported
# using yarn's new build and package installation procedures. This is
# why we currently use nodeLinker. In this future, this option may
# not be required. For now though:
# https://yarnpkg.com/configuration/yarnrc#nodeLinker
nodeLinker: node-modules
