/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../cms/schema.json
export type MemberReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'member'
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  president?: MemberReference
  editorInChief?: MemberReference
}

export type Tag = {
  _id: string
  _type: 'tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: RequiredFormattedString
  slug: Slug
  description: RequiredFormattedText
  metaInfo?: MetaInfo
  copypaste?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type MetaInfo = {
  _type: 'metaInfo'
  ogTitle?: FormattedString
  ogTags?: Array<
    {
      _key: string
    } & SeoMetadataTagText
  >
  ogDescription?: FormattedText
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: RequiredFormattedString
    _type: 'image'
  }
}

export type RequiredFormattedText = string

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type RequiredFormattedString = string

export type CommitteeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'committee'
}

export type Member = {
  _id: string
  _type: 'member'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: RequiredFormattedString
  slug: Slug
  year?: number
  committee?: CommitteeReference
  netid?: FormattedString
  bio?: FormattedText
  from?: FromLocation
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  handles?: Handles
  metaInfo?: MetaInfo
  copypaste?: string
}

export type Handles = {
  _type: 'handles'
  twitter?: FormattedString
  instagram?: FormattedString
  facebook?: FormattedString
  linkedin?: FormattedString
  github?: FormattedString
  website?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type FromLocation = {
  _type: 'fromLocation'
  country?:
    | 'AF'
    | 'AL'
    | 'DZ'
    | 'AD'
    | 'AO'
    | 'AG'
    | 'AR'
    | 'AM'
    | 'AU'
    | 'AT'
    | 'AZ'
    | 'BS'
    | 'BH'
    | 'BD'
    | 'BB'
    | 'BY'
    | 'BE'
    | 'BZ'
    | 'BJ'
    | 'BT'
    | 'BO'
    | 'BA'
    | 'BW'
    | 'BR'
    | 'BN'
    | 'BG'
    | 'BF'
    | 'BI'
    | 'CV'
    | 'KH'
    | 'CM'
    | 'CA'
    | 'CF'
    | 'TD'
    | 'CL'
    | 'CN'
    | 'CO'
    | 'KM'
    | 'CG'
    | 'CD'
    | 'CR'
    | 'HR'
    | 'CU'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'DJ'
    | 'DM'
    | 'DO'
    | 'EC'
    | 'EG'
    | 'SV'
    | 'GQ'
    | 'ER'
    | 'EE'
    | 'SZ'
    | 'ET'
    | 'FJ'
    | 'FI'
    | 'FR'
    | 'GA'
    | 'GM'
    | 'GE'
    | 'DE'
    | 'GH'
    | 'GR'
    | 'GD'
    | 'GT'
    | 'GN'
    | 'GW'
    | 'GY'
    | 'HT'
    | 'HN'
    | 'HU'
    | 'IS'
    | 'IN'
    | 'ID'
    | 'IR'
    | 'IQ'
    | 'IE'
    | 'IL'
    | 'IT'
    | 'JM'
    | 'JP'
    | 'JO'
    | 'KZ'
    | 'KE'
    | 'KI'
    | 'KP'
    | 'KR'
    | 'KW'
    | 'KG'
    | 'LA'
    | 'LV'
    | 'LB'
    | 'LS'
    | 'LR'
    | 'LY'
    | 'LI'
    | 'LT'
    | 'LU'
    | 'MG'
    | 'MW'
    | 'MY'
    | 'MV'
    | 'ML'
    | 'MT'
    | 'MH'
    | 'MR'
    | 'MU'
    | 'MX'
    | 'FM'
    | 'MD'
    | 'MC'
    | 'MN'
    | 'ME'
    | 'MA'
    | 'MZ'
    | 'MM'
    | 'NA'
    | 'NR'
    | 'NP'
    | 'NL'
    | 'NZ'
    | 'NI'
    | 'NE'
    | 'NG'
    | 'MK'
    | 'NO'
    | 'OM'
    | 'PK'
    | 'PW'
    | 'PA'
    | 'PG'
    | 'PY'
    | 'PE'
    | 'PH'
    | 'PL'
    | 'PT'
    | 'QA'
    | 'RO'
    | 'RU'
    | 'RW'
    | 'KN'
    | 'LC'
    | 'VC'
    | 'WS'
    | 'SM'
    | 'ST'
    | 'SA'
    | 'SN'
    | 'RS'
    | 'SC'
    | 'SL'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'SB'
    | 'SO'
    | 'ZA'
    | 'SS'
    | 'ES'
    | 'LK'
    | 'SD'
    | 'SR'
    | 'SE'
    | 'CH'
    | 'SY'
    | 'TJ'
    | 'TH'
    | 'TL'
    | 'TG'
    | 'TO'
    | 'TT'
    | 'TN'
    | 'TR'
    | 'TM'
    | 'TV'
    | 'UG'
    | 'UA'
    | 'AE'
    | 'GB'
    | 'US'
    | 'UY'
    | 'UZ'
    | 'VU'
    | 'VE'
    | 'VN'
    | 'YE'
    | 'ZM'
    | 'ZW'
  region?: FormattedString
  city?: FormattedString
}

export type FormattedText = string

export type FormattedString = string

export type Committee = {
  _id: string
  _type: 'committee'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: RequiredFormattedString
  slug: Slug
  description: RequiredFormattedText
  useCustomCss?: boolean
  metaInfo?: MetaInfo
  copypaste?: string
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type SeriesReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'series'
}

export type TagReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'tag'
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: RequiredFormattedString
  slug: Slug
  subtitle?: FormattedText
  date: string
  updatedDate?: string
  category: CategoryReference
  series?: SeriesReference
  tags?: Array<
    {
      _key: string
    } & TagReference
  >
  authors: Array<
    {
      _key: string
    } & MemberReference
  >
  media?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  }
  abstract?: FormattedText
  content: Content
  useCustomCss?: boolean
  metaInfo?: MetaInfo
}

export type Content = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote' | 'blockComment'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      title?: FormattedString
      description?: FormattedText
      alt: RequiredFormattedString
      _type: 'image'
      _key: string
    }
  | ({
      _key: string
    } & EmbeddedLink)
>

export type Series = {
  _id: string
  _type: 'series'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: RequiredFormattedString
  slug: Slug
  description: RequiredFormattedText
  useCustomCss?: boolean
  metaInfo?: MetaInfo
  copypaste?: string
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: RequiredFormattedString
  slug: Slug
  description: RequiredFormattedText
  useCustomCss?: boolean
  metaInfo?: MetaInfo
  copypaste?: string
}

export type SeoMetadataTagText = string

export type AccessibleImage = {
  _type: 'accessibleImage'
  media?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    description?: FormattedText
    attributions?: FormattedString
    _type: 'image'
  }
}

export type DateInfo = {
  _type: 'dateInfo'
  published: string
  updated?: string
}

export type EmbeddedLink = {
  _type: 'embeddedLink'
  contentUrl: string
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | MemberReference
  | AboutPage
  | Tag
  | SanityImageAssetReference
  | MetaInfo
  | RequiredFormattedText
  | Slug
  | RequiredFormattedString
  | CommitteeReference
  | Member
  | Handles
  | SanityImageCrop
  | SanityImageHotspot
  | FromLocation
  | FormattedText
  | FormattedString
  | Committee
  | CategoryReference
  | SeriesReference
  | TagReference
  | Article
  | Content
  | Series
  | Category
  | SeoMetadataTagText
  | AccessibleImage
  | DateInfo
  | EmbeddedLink
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/lib/sanity/queries.ts
// Variable: maybeAllMembersQuery
// Query: *[_type == "member"] | order(lower(name) asc) {			_id,	name,	"slug": slug.current,		bio	}
export type MaybeAllMembersQueryResult = Array<{
  _id: string
  name: RequiredFormattedString
  slug: string
  bio: FormattedText | null
}>

// Source: src/lib/sanity/queries.ts
// Variable: maybeMemberQuery
// Query: *[_type == "member" && _id == $id] {			_id,	name,	"slug": slug.current	}[0]
export type MaybeMemberQueryResult = {
  _id: string
  name: RequiredFormattedString
  slug: string
} | null

// Source: src/lib/sanity/queries.ts
// Variable: maybeMemberPageQuery
// Query: *[_type == "member" && slug.current == $slug] {			_id,	name,	"slug": slug.current,			year,	bio,	handles,	from,	portrait { ..., asset-> },	committee->{ name },		metaInfo	}[0]
export type MaybeMemberPageQueryResult = {
  _id: string
  name: RequiredFormattedString
  slug: string
  year: number | null
  bio: FormattedText | null
  handles: Handles | null
  from: FromLocation | null
  portrait: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  committee: {
    name: RequiredFormattedString
  } | null
  metaInfo: MetaInfo | null
} | null

// Source: src/lib/sanity/queries.ts
// Variable: maybeCategoryPageQuery
// Query: *[_type == "category" && slug.current == $slug] {			_id,	name,	"slug": slug.current,		description,		useCustomCss,		metaInfo	}[0]
export type MaybeCategoryPageQueryResult = {
  _id: string
  name: RequiredFormattedString
  slug: string
  description: RequiredFormattedText
  useCustomCss: boolean | null
  metaInfo: MetaInfo | null
} | null

// Source: src/lib/sanity/queries.ts
// Variable: maybeCategoryPagePaginateArticlesQuery
// Query: *[_type == "article" && category->slug.current == $slug && (date > $lastDate || (date > $lastDate && _id > $lastId))] | order(date desc) [0..15] {				_id,	_type,		title,	"slug": slug.current,	subtitle,	date,	updatedDate,	authors[]->{ 	_id,	name,	"slug": slug.current },	tags[]->{ 	_id,	name,	"slug": slug.current },	category->{ 	_id,	name,	"slug": slug.current },	series->{ 	_id,	name,	"slug": slug.current },	media,		media {		...,		asset->{			...,			creditLine    }	}	}
export type MaybeCategoryPagePaginateArticlesQueryResult = Array<{
  _id: string
  _type: 'article'
  title: RequiredFormattedString
  slug: string
  subtitle: FormattedText | null
  date: string
  updatedDate: string | null
  authors: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }>
  tags: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }> | null
  category: {
    _id: string
    name: RequiredFormattedString
    slug: string
  }
  series: {
    _id: string
    name: RequiredFormattedString
    slug: string
  } | null
  media: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
      creditLine: null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  } | null
}>

// Source: src/lib/sanity/queries.ts
// Variable: maybeCategoryPageInitialArticlesQuery
// Query: *[_type == "article" && category->slug.current == $slug] | order(date desc) [0..15] {				_id,	_type,		title,	"slug": slug.current,	subtitle,	date,	updatedDate,	authors[]->{ 	_id,	name,	"slug": slug.current },	tags[]->{ 	_id,	name,	"slug": slug.current },	category->{ 	_id,	name,	"slug": slug.current },	series->{ 	_id,	name,	"slug": slug.current },	media,		media {		...,		asset->{			...,			creditLine    }	}	}
export type MaybeCategoryPageInitialArticlesQueryResult = Array<{
  _id: string
  _type: 'article'
  title: RequiredFormattedString
  slug: string
  subtitle: FormattedText | null
  date: string
  updatedDate: string | null
  authors: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }>
  tags: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }> | null
  category: {
    _id: string
    name: RequiredFormattedString
    slug: string
  }
  series: {
    _id: string
    name: RequiredFormattedString
    slug: string
  } | null
  media: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
      creditLine: null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  } | null
}>

// Source: src/lib/sanity/queries.ts
// Variable: maybeSeriesPageQuery
// Query: *[_type == "series" && slug.current == $slug] {			_id,	name,	"slug": slug.current,		description,		useCustomCss,		metaInfo	}[0]
export type MaybeSeriesPageQueryResult = {
  _id: string
  name: RequiredFormattedString
  slug: string
  description: RequiredFormattedText
  useCustomCss: boolean | null
  metaInfo: MetaInfo | null
} | null

// Source: src/lib/sanity/queries.ts
// Variable: maybeSeriesPageInitialArticlesQuery
// Query: *[_type == "article" && series->slug.current == $slug] | order(date desc) [0..15] {				_id,	_type,		title,	"slug": slug.current,	subtitle,	date,	updatedDate,	authors[]->{ 	_id,	name,	"slug": slug.current },	tags[]->{ 	_id,	name,	"slug": slug.current },	category->{ 	_id,	name,	"slug": slug.current },	series->{ 	_id,	name,	"slug": slug.current },	media,		media {		...,		asset->{			...,			creditLine    }	}	}
export type MaybeSeriesPageInitialArticlesQueryResult = Array<{
  _id: string
  _type: 'article'
  title: RequiredFormattedString
  slug: string
  subtitle: FormattedText | null
  date: string
  updatedDate: string | null
  authors: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }>
  tags: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }> | null
  category: {
    _id: string
    name: RequiredFormattedString
    slug: string
  }
  series: {
    _id: string
    name: RequiredFormattedString
    slug: string
  } | null
  media: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
      creditLine: null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  } | null
}>

// Source: src/lib/sanity/queries.ts
// Variable: maybeAllSeriesQuery
// Query: *[_type == "series" && count(*[_type == "article" && references(^._id)]) >= 1] | order(lower(name) asc) {			_id,	name,	"slug": slug.current,		description	}
export type MaybeAllSeriesQueryResult = Array<{
  _id: string
  name: RequiredFormattedString
  slug: string
  description: RequiredFormattedText
}>

// Source: src/lib/sanity/queries.ts
// Variable: maybeAllTagsQuery
// Query: *[_type == "tag"] | order(lower(name) asc) {			_id,	name,	"slug": slug.current	}
export type MaybeAllTagsQueryResult = Array<{
  _id: string
  name: RequiredFormattedString
  slug: string
}>

// Source: src/lib/sanity/queries.ts
// Variable: maybeTagPageQuery
// Query: *[_type == "tag" && slug.current == $slug] {			_id,	name,	"slug": slug.current,		description,		metaInfo	}[0]
export type MaybeTagPageQueryResult = {
  _id: string
  name: RequiredFormattedString
  slug: string
  description: RequiredFormattedText
  metaInfo: MetaInfo | null
} | null

// Source: src/lib/sanity/queries.ts
// Variable: maybeTagPageInitialArticlesQuery
// Query: *[_type == "article" && $slug in tags[]->slug.current] | order(date desc) [0..15] {				_id,	_type,		title,	"slug": slug.current,	subtitle,	date,	updatedDate,	authors[]->{ 	_id,	name,	"slug": slug.current },	tags[]->{ 	_id,	name,	"slug": slug.current },	category->{ 	_id,	name,	"slug": slug.current },	series->{ 	_id,	name,	"slug": slug.current },	media,		media {		...,		asset->{			...,			creditLine    }	}	}
export type MaybeTagPageInitialArticlesQueryResult = Array<{
  _id: string
  _type: 'article'
  title: RequiredFormattedString
  slug: string
  subtitle: FormattedText | null
  date: string
  updatedDate: string | null
  authors: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }>
  tags: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }> | null
  category: {
    _id: string
    name: RequiredFormattedString
    slug: string
  }
  series: {
    _id: string
    name: RequiredFormattedString
    slug: string
  } | null
  media: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
      creditLine: null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  } | null
}>

// Source: src/lib/sanity/queries.ts
// Variable: maybeSingleMemberArticlesQuery
// Query: *[_type == "article" && references(*[_type == "member" && slug.current == $slug]._id)] | order(date desc) {				_id,	_type,		title,	"slug": slug.current,	subtitle,	date,	updatedDate,	authors[]->{ 	_id,	name,	"slug": slug.current },	tags[]->{ 	_id,	name,	"slug": slug.current },	category->{ 	_id,	name,	"slug": slug.current },	series->{ 	_id,	name,	"slug": slug.current },	media,		media {		...,		asset->{			...,			creditLine    }	}	}
export type MaybeSingleMemberArticlesQueryResult = Array<{
  _id: string
  _type: 'article'
  title: RequiredFormattedString
  slug: string
  subtitle: FormattedText | null
  date: string
  updatedDate: string | null
  authors: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }>
  tags: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }> | null
  category: {
    _id: string
    name: RequiredFormattedString
    slug: string
  }
  series: {
    _id: string
    name: RequiredFormattedString
    slug: string
  } | null
  media: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
      creditLine: null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  } | null
}>

// Source: src/lib/sanity/queries.ts
// Variable: homepageArticleQuery
// Query: *[_type == "article" && category.slug.current != "multimedia"] | order(date desc) [0..15] {				_id,	_type,		title,	"slug": slug.current,	subtitle,	date,	updatedDate,	authors[]->{ 	_id,	name,	"slug": slug.current },	tags[]->{ 	_id,	name,	"slug": slug.current },	category->{ 	_id,	name,	"slug": slug.current },	series->{ 	_id,	name,	"slug": slug.current },	media,		media {		...,		asset->{			...,			creditLine    }	}	}
export type HomepageArticleQueryResult = Array<{
  _id: string
  _type: 'article'
  title: RequiredFormattedString
  slug: string
  subtitle: FormattedText | null
  date: string
  updatedDate: string | null
  authors: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }>
  tags: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }> | null
  category: {
    _id: string
    name: RequiredFormattedString
    slug: string
  }
  series: {
    _id: string
    name: RequiredFormattedString
    slug: string
  } | null
  media: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
      creditLine: null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  } | null
}>

// Source: src/lib/sanity/queries.ts
// Variable: sitemapArticlesDataQuery
// Query: *[_type == "article"] {		'slug': slug.current,		'category': category->slug.current,		'date': coalesce(updatedDate, date),	}
export type SitemapArticlesDataQueryResult = Array<{
  slug: string
  category: string
  date: string
}>

// Source: src/lib/sanity/queries.ts
// Variable: maybeArticlePageQuery
// Query: *[_type == "article" && category->slug.current == $category && slug.current == $slug]{				_id,	_type,		title,	"slug": slug.current,	subtitle,	date,	updatedDate,	authors[]->{ 	_id,	name,	"slug": slug.current },	tags[]->{ 	_id,	name,	"slug": slug.current },	category->{ 	_id,	name,	"slug": slug.current },	series->{ 	_id,	name,	"slug": slug.current },	media,		media {		...,		asset->{			...,			creditLine    }	},		metaInfo,		content[]{			...,			_type == "image" => {				...,				...asset-> { metadata, creditLine },			}		},	}[0]
export type MaybeArticlePageQueryResult = {
  _id: string
  _type: 'article'
  title: RequiredFormattedString
  slug: string
  subtitle: FormattedText | null
  date: string
  updatedDate: string | null
  authors: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }>
  tags: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }> | null
  category: {
    _id: string
    name: RequiredFormattedString
    slug: string
  }
  series: {
    _id: string
    name: RequiredFormattedString
    slug: string
  } | null
  media: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
      creditLine: null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  } | null
  metaInfo: MetaInfo | null
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockComment' | 'blockquote' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        _key: string
        _type: 'embeddedLink'
        contentUrl: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        title?: FormattedString
        description?: FormattedText
        alt: RequiredFormattedString
        _type: 'image'
        _key: string
        metadata: SanityImageMetadata | null
        creditLine: null
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        title?: FormattedString
        description?: FormattedText
        alt: RequiredFormattedString
        _type: 'image'
        _key: string
      }
  >
} | null

// Source: src/lib/sanity/queries.ts
// Variable: maybeSingleArticleQuery
// Query: *[_type == "article" && category->slug.current == $category && slug.current == $slug]{				_id,	_type,		title,	"slug": slug.current,	subtitle,	date,	updatedDate,	authors[]->{ 	_id,	name,	"slug": slug.current },	tags[]->{ 	_id,	name,	"slug": slug.current },	category->{ 	_id,	name,	"slug": slug.current },	series->{ 	_id,	name,	"slug": slug.current },	media,		media {		...,		asset->{			...,			creditLine    }	},		metaInfo	}[0]
export type MaybeSingleArticleQueryResult = {
  _id: string
  _type: 'article'
  title: RequiredFormattedString
  slug: string
  subtitle: FormattedText | null
  date: string
  updatedDate: string | null
  authors: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }>
  tags: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }> | null
  category: {
    _id: string
    name: RequiredFormattedString
    slug: string
  }
  series: {
    _id: string
    name: RequiredFormattedString
    slug: string
  } | null
  media: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
      creditLine: null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  } | null
  metaInfo: MetaInfo | null
} | null

// Source: src/lib/sanity/queries.ts
// Variable: relatedArticlesTypeA
// Query: *[_type == "article" && slug.current != $slug] | score(    boost(author._ref in $authors, 4),    boost(date match $date, 1.5),    boost(title match $title, 1.2),    boost(category._ref match $categoryId, 2.3),    // boost(content[].children[].text match $content, 4),  ) | order(_score desc) [0..8] {    _score,				_id,	_type,		title,	"slug": slug.current,	subtitle,	date,	updatedDate,	authors[]->{ 	_id,	name,	"slug": slug.current },	tags[]->{ 	_id,	name,	"slug": slug.current },	category->{ 	_id,	name,	"slug": slug.current },	series->{ 	_id,	name,	"slug": slug.current },	media,		media {		...,		asset->{			...,			creditLine    }	}  } //[ _score > 0 ]
export type RelatedArticlesTypeAResult = Array<{
  _score: null
  _id: string
  _type: 'article'
  title: RequiredFormattedString
  slug: string
  subtitle: FormattedText | null
  date: string
  updatedDate: string | null
  authors: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }>
  tags: Array<{
    _id: string
    name: RequiredFormattedString
    slug: string
  }> | null
  category: {
    _id: string
    name: RequiredFormattedString
    slug: string
  }
  series: {
    _id: string
    name: RequiredFormattedString
    slug: string
  } | null
  media: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
      creditLine: null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: RequiredFormattedString
    _type: 'image'
  } | null
}>

// Source: src/lib/sanity/queries.ts
// Variable: sitemapAuthorsQuery
// Query: *[_type == "member"] {		'slug': slug.current,		updatedAt	}
export type SitemapAuthorsQueryResult = Array<{
  slug: string
  updatedAt: null
}>

// Source: src/lib/sanity/queries.ts
// Variable: sitemapArticlesQuery
// Query: *[_type == "article"] {		'slug': slug.current,		'category': category->slug.current,		'date': coalesce(updatedDate, date),	}
export type SitemapArticlesQueryResult = Array<{
  slug: string
  category: string
  date: string
}>

// Source: src/lib/sanity/queries.ts
// Variable: sitemapSeriesQuery
// Query: *[_type == "series"] {		'slug': slug.current,		date	}
export type SitemapSeriesQueryResult = Array<{
  slug: string
  date: null
}>

// Source: src/lib/sanity/queries.ts
// Variable: sitemapTagsQuery
// Query: *[_type == "tag"] {		'slug': slug.current,		date	}
export type SitemapTagsQueryResult = Array<{
  slug: string
  date: null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n\t*[_type == "member"] | order(lower(name) asc) {\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current\n,\n\t\tbio\n\t}\n': MaybeAllMembersQueryResult
    '\n\t*[_type == "member" && _id == $id] {\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current\n\n\t}[0]\n': MaybeMemberQueryResult
    '\n\t*[_type == "member" && slug.current == $slug] {\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current\n,\n\t\t\n\tyear,\n\tbio,\n\thandles,\n\tfrom,\n\tportrait { ..., asset-> },\n\tcommittee->{ name }\n,\n\t\tmetaInfo\n\t}[0]\n': MaybeMemberPageQueryResult
    '\n\t*[_type == "category" && slug.current == $slug] {\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current\n,\n\t\tdescription,\n\t\tuseCustomCss,\n\t\tmetaInfo\n\t}[0]\n': MaybeCategoryPageQueryResult
    '\n\t*[_type == "article" && category->slug.current == $slug && (date > $lastDate || (date > $lastDate && _id > $lastId))] | order(date desc) [0..15] {\n\t\t\n\t\n\t_id,\n\t_type\n,\n\t\n\ttitle,\n\t"slug": slug.current,\n\tsubtitle,\n\tdate,\n\tupdatedDate,\n\tauthors[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\ttags[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tcategory->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tseries->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tmedia\n,\n\t\n\tmedia {\n\t\t...,\n\t\tasset->{\n\t\t\t...,\n\t\t\tcreditLine\n    }\n\t}\n\n\n\t}\n': MaybeCategoryPagePaginateArticlesQueryResult
    '\n\t*[_type == "article" && category->slug.current == $slug] | order(date desc) [0..15] {\n\t\t\n\t\n\t_id,\n\t_type\n,\n\t\n\ttitle,\n\t"slug": slug.current,\n\tsubtitle,\n\tdate,\n\tupdatedDate,\n\tauthors[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\ttags[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tcategory->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tseries->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tmedia\n,\n\t\n\tmedia {\n\t\t...,\n\t\tasset->{\n\t\t\t...,\n\t\t\tcreditLine\n    }\n\t}\n\n\n\t}\n': MaybeCategoryPageInitialArticlesQueryResult
    '\n\t*[_type == "series" && slug.current == $slug] {\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current\n,\n\t\tdescription,\n\t\tuseCustomCss,\n\t\tmetaInfo\n\t}[0]\n': MaybeSeriesPageQueryResult
    '\n\t*[_type == "article" && series->slug.current == $slug] | order(date desc) [0..15] {\n\t\t\n\t\n\t_id,\n\t_type\n,\n\t\n\ttitle,\n\t"slug": slug.current,\n\tsubtitle,\n\tdate,\n\tupdatedDate,\n\tauthors[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\ttags[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tcategory->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tseries->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tmedia\n,\n\t\n\tmedia {\n\t\t...,\n\t\tasset->{\n\t\t\t...,\n\t\t\tcreditLine\n    }\n\t}\n\n\n\t}\n': MaybeSeriesPageInitialArticlesQueryResult
    '\n\t*[_type == "series" && count(*[_type == "article" && references(^._id)]) >= 1] | order(lower(name) asc) {\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current\n,\n\t\tdescription\n\t}\n': MaybeAllSeriesQueryResult
    '\n\t*[_type == "tag"] | order(lower(name) asc) {\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current\n\n\t}\n': MaybeAllTagsQueryResult
    '\n\t*[_type == "tag" && slug.current == $slug] {\n\t\t\n\t_id,\n\tname,\n\t"slug": slug.current\n,\n\t\tdescription,\n\t\tmetaInfo\n\t}[0]\n': MaybeTagPageQueryResult
    '\n\t*[_type == "article" && $slug in tags[]->slug.current] | order(date desc) [0..15] {\n\t\t\n\t\n\t_id,\n\t_type\n,\n\t\n\ttitle,\n\t"slug": slug.current,\n\tsubtitle,\n\tdate,\n\tupdatedDate,\n\tauthors[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\ttags[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tcategory->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tseries->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tmedia\n,\n\t\n\tmedia {\n\t\t...,\n\t\tasset->{\n\t\t\t...,\n\t\t\tcreditLine\n    }\n\t}\n\n\n\t}\n': MaybeTagPageInitialArticlesQueryResult
    '\n\t*[_type == "article" && references(*[_type == "member" && slug.current == $slug]._id)] | order(date desc) {\n\t\t\n\t\n\t_id,\n\t_type\n,\n\t\n\ttitle,\n\t"slug": slug.current,\n\tsubtitle,\n\tdate,\n\tupdatedDate,\n\tauthors[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\ttags[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tcategory->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tseries->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tmedia\n,\n\t\n\tmedia {\n\t\t...,\n\t\tasset->{\n\t\t\t...,\n\t\t\tcreditLine\n    }\n\t}\n\n\n\t}\n': MaybeSingleMemberArticlesQueryResult
    '\n\t*[_type == "article" && category.slug.current != "multimedia"] | order(date desc) [0..15] {\n\t\t\n\t\n\t_id,\n\t_type\n,\n\t\n\ttitle,\n\t"slug": slug.current,\n\tsubtitle,\n\tdate,\n\tupdatedDate,\n\tauthors[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\ttags[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tcategory->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tseries->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tmedia\n,\n\t\n\tmedia {\n\t\t...,\n\t\tasset->{\n\t\t\t...,\n\t\t\tcreditLine\n    }\n\t}\n\n\n\t}\n': HomepageArticleQueryResult
    "\n\t*[_type == \"article\"] {\n\t\t'slug': slug.current,\n\t\t'category': category->slug.current,\n\t\t'date': coalesce(updatedDate, date),\n\t}\n":
      | SitemapArticlesDataQueryResult
      | SitemapArticlesQueryResult
    '\n\t*[_type == "article" && category->slug.current == $category && slug.current == $slug]{\n\t\t\n\t\n\t_id,\n\t_type\n,\n\t\n\ttitle,\n\t"slug": slug.current,\n\tsubtitle,\n\tdate,\n\tupdatedDate,\n\tauthors[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\ttags[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tcategory->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tseries->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tmedia\n,\n\t\n\tmedia {\n\t\t...,\n\t\tasset->{\n\t\t\t...,\n\t\t\tcreditLine\n    }\n\t}\n\n,\n\t\tmetaInfo,\n\t\tcontent[]{\n\t\t\t...,\n\t\t\t_type == "image" => {\n\t\t\t\t...,\n\t\t\t\t...asset-> { metadata, creditLine },\n\t\t\t}\n\t\t},\n\t}[0]\n': MaybeArticlePageQueryResult
    '\n\t*[_type == "article" && category->slug.current == $category && slug.current == $slug]{\n\t\t\n\t\n\t_id,\n\t_type\n,\n\t\n\ttitle,\n\t"slug": slug.current,\n\tsubtitle,\n\tdate,\n\tupdatedDate,\n\tauthors[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\ttags[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tcategory->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tseries->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tmedia\n,\n\t\n\tmedia {\n\t\t...,\n\t\tasset->{\n\t\t\t...,\n\t\t\tcreditLine\n    }\n\t}\n\n,\n\t\tmetaInfo\n\t}[0]\n': MaybeSingleArticleQueryResult
    '\n  *[_type == "article" && slug.current != $slug] | score(\n    boost(author._ref in $authors, 4),\n    boost(date match $date, 1.5),\n    boost(title match $title, 1.2),\n    boost(category._ref match $categoryId, 2.3),\n    // boost(content[].children[].text match $content, 4),\n  ) | order(_score desc) [0..8] {\n    _score,\n\t\t\n\t\n\t_id,\n\t_type\n,\n\t\n\ttitle,\n\t"slug": slug.current,\n\tsubtitle,\n\tdate,\n\tupdatedDate,\n\tauthors[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\ttags[]->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tcategory->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tseries->{ \n\t_id,\n\tname,\n\t"slug": slug.current\n },\n\tmedia\n,\n\t\n\tmedia {\n\t\t...,\n\t\tasset->{\n\t\t\t...,\n\t\t\tcreditLine\n    }\n\t}\n\n\n  } //[ _score > 0 ]\n': RelatedArticlesTypeAResult
    '\n\t*[_type == "member"] {\n\t\t\'slug\': slug.current,\n\t\tupdatedAt\n\t}\n': SitemapAuthorsQueryResult
    '\n\t*[_type == "series"] {\n\t\t\'slug\': slug.current,\n\t\tdate\n\t}\n': SitemapSeriesQueryResult
    '\n\t*[_type == "tag"] {\n\t\t\'slug\': slug.current,\n\t\tdate\n\t}\n': SitemapTagsQueryResult
  }
}
