# Inspired from: https://github.com/syncthing/syncthing/blob/main/.github/ISSUE_TEMPLATE/01-feature.yml

name: Feature request
description: Suggest a feature or implementation.
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the feature. Make it clear and concise if you can.
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links
      description: Links you may find useful to the implementation of this feature.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
