name: Task
description: Create a task to do.
type: task
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the Task. Make it clear and concise if you can.
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links
      description: Useful or relevant links to aid this Task.
    validations:
      required: false
