# Inspired from: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# As well as: https://github.com/syncthing/syncthing/blob/main/.github/ISSUE_TEMPLATE/02-bug.yml

name: Bug report
description: Describe unexpected behavior or dysfunctional implementation.
labels: ["bug"]
assignees:
  - yulanhua
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is and the expected behavior.
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform & operating system
      description: On what platform(s) are you seeing the problem?
      placeholder: Linux arm64
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Steps to reproduce
      description: Enumerated list of steps to reproduce the unexpected behavior or dysfunctional implementation.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
