# Inspired from: https://github.com/syncthing/syncthing/blob/main/.github/ISSUE_TEMPLATE/01-feature.yml

name: Feature
description: Suggest a new feature.
type: feature
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the Feature. Make it clear and concise if you can.
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links
      description: Useful or relevant links to aid this Feature implementation.
    validations:
      required: false
