name = "frontend"
vars = { ENVIRONMENT = "dev" }
main = ".svelte-kit/cloudflare/_worker.js"
routes = [{ pattern = "dev.onmagnoliasquare.com", custom_domain = true }]

compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-08-07"

assets = { binding = "ASSETS", directory = ".svelte-kit/cloudflare" }
observability = { enabled = true }
placement = { mode = "smart" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
routes = [{ pattern = "staging.onmagnoliasquare.com", custom_domain = true }]

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [{ pattern = "onmagnoliasquare.com", custom_domain = true }]
