name: Get yarn version
description: |
  Retrieve Yarn version from package.json and set it as an environment variable and output

inputs:
  package_json_path:
    description: Path to the package.json file
    required: false
    default: './package.json'

outputs:
  yarn_version:
    description: Yarn version extracted from package.json

runs:
  using: "composite"
  steps:
    # Retrieve yarn version from package.json
    - name: Get yarn version from package.json
      shell: bash
      run: |
        grep 'packageManager' package.json | awk -F: '{gsub(/[", ]/, "", $2); print $2}' | xargs -I {} echo "YARN_VERSION="{} >> "$GITHUB_ENV"

    # Set the yarn version by exporting to env var and output
    - name: Append yarn version to $GITHUB_OUTPUT
      shell: bash
      id: set_yarn_version
      run: |
        echo "yarn_version=${{ env.YARN_VERSION }}" >> "$GITHUB_OUTPUT"

