# https://stackoverflow.com/questions/71120146/allowing-only-certain-branches-to-pr-merge-to-mainmaster-branch
name: "Enforce Dev to Staging"

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'staging' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge to staging from dev."
          exit 1
