name: Deploy staging

on:
  push:
    branches: ['staging']
  workflow_dispatch:

jobs:
  changes:
    name: Check changes
    runs-on: ubuntu-${{vars.RUNNER_VERSION}}
    permissions:
      pull-requests: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: dev
          # base: ${{ github.ref_name }}
          list-files: csv
          filters: |
            frontend:
              - 'packages/frontend/**'
            backend:
              - 'packages/backend/**'
      - name: Log all filter results
        run: |
          echo "frontend: ${{ steps.filter.outputs.frontend }}"
          echo "backend: ${{ steps.filter.outputs.backend }}"

  build:
    name: Set yarn and build artifacts
    runs-on: ubuntu-${{vars.RUNNER_VERSION}}
    outputs:
      yarn_version: ${{ steps.set_yarn_version.outputs.yarn_version }}
    needs: [changes]
    environment: staging
    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true' }}
    steps:
      - uses: actions/checkout@v4

      # Retrieve yarn version from package.json
      - name: Get yarn version from package.json
        run: |
          grep 'packageManager' package.json | awk -F: '{gsub(/[", ]/, "", $2); print $2}' | xargs -I {} echo "YARN_VERSION="{} >> "$GITHUB_ENV"

      # Set the yarn version by exporting to env var and output
      - name: Append yarn version to $GITHUB_OUTPUT
        id: set_yarn_version
        run: |
          echo "yarn_version=${{ env.YARN_VERSION }}" >> "$GITHUB_OUTPUT"

      - name: Node setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ vars.NODE_VERSION }}
          yarn-version: ${{ steps.set_yarn_version.outputs.yarn_version }}
          yarn-install-cache-key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Build frontend for staging
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        run: yarn workspace frontend build:staging

      - name: Build backend for staging
        if: ${{ needs.changes.outputs.backend == 'true' }}
        run: yarn workspace backend build

      # Cache the build after all is said and done.
      # This build will be used in the following jobs.
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

  deploy-staging:
    name: Deploy to development environment
    needs: [build, changes]
    if: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}
    env:
      YARN_VERSION: ${{ needs.build.outputs.yarn_version }}
    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Node setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ vars.NODE_VERSION }}
          yarn-version: ${{ env.YARN_VERSION  }}
          yarn-run-install: false
          yarn-restore-cache: false # We restore the build from actions/cache
          yarn-install-cache-key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Restore build
        uses: actions/cache@v4
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Publish frontend to Cloudflare Pages
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy packages/frontend/.svelte-kit/cloudflare --project-name=website
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      # Deploy backend artifact
