name: "Run Tests"

on:
  pull_request:
    branches: ["main", "staging", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run backend tests
        run: yarn test:back

      - name: Run frontend tests
        run: yarn test:front
